= Spring Framework 7
:toc:
:toc-placement:
:toclevels: 3

Spring Framework 7 will release in November 2025.

== Minimum requirement changes

Certain baselines have been raised, so keep these in mind if you're using them:

* A Servlet 6.1 compatible container
* JPA 3.2
* Bean Validation 3.1
* GraalVM 24 with the https://www.graalvm.org/latest/reference-manual/native-image/metadata/[new extract reachability metadata format]
* Kotlin 2.2
*  Netty 4.2
* JSONAssert 2.0

== Upgrading

=== Spring JCL has been retired

This module has been removed in favour of Apache commons logging, as this was a transitive dependency and the API calls aren't changing you should experience no impact.

=== Removal of support for `javax.annotation` and `java.inject`

These annotations are no longer supported, and the `jakarta` equivalent should be used.

=== Removal of deprecated path mapping options

The path mapping options that were marked as deprecated in 6.0 have been removed.

For example:

* `matchOptionalTrailingSeparator`
* `ignoreUnknownPathExtensions`
* `trailingSlashMatch`
* `PathExtensionContentNegotiationStrategy`

== New

=== RestTestClient

This non-reactive variant of `WebTestClient` can be used toi test live servers, and mock setups with a fluent API.
It can be bound to a live server, an MVC `@Controller` or the application context.

I recommend looking at the https://docs.spring.io/spring-framework/reference/7.0-SNAPSHOT/testing/resttestclient.html#page-title[official documentation].

=== Test application context pausing

As of this release an application context cache in the test context cache will be stopped when it is no longer in active use, and will automatically restart it as needed. This helps reduce the number of running background processes.

== Thoughts

== References

* https://github.com/spring-projects/spring-framework/wiki/Spring-Framework-7.0-Release-Notes [Spring framework 7 release notes]