= Spring Framework 7
:toc:
:toc-placement:
:toclevels: 3

Spring Framework 7 will be released in November 2025.

== Minimum requirement changes

Certain baselines have been raised, so keep these in mind if you're using them:

* A Servlet 6.1 compatible container
* JPA 3.2 (Hibernate ORM 7.1/7.2)
* Bean Validation 3.1 (Hibernate Validator 9.0/9.1)
* GraalVM 24 with the https://www.graalvm.org/latest/reference-manual/native-image/metadata/[new extract reachability metadata format]
* Kotlin 2.2
* Netty 4.2
* JUnit 6

== Upgrading

=== `javax.annotation.*` and `javax.inject.*` annotations are no longer supported

Support for these annotations in `javax` has been dropped, if your application still uses these please migrate to the `jakarta` equivalent.

For example, `javax.annotation.PostConstruct` will become `jakarta.annotation.PostConstruct`.

=== SpringExtension - potentially breaking

The `SpringExtension` which integrates the Spring TestContext Framework into JUnit Jupiter, has been adapted to use a test-method scoped `ExtensionContext`.
This change facilitates consistent dependency injection semantics in `@Nested` test class hierarchies.

There are 2 cases in which you may notice some breaking tests:

1) If you have custom `TestExecutionListener` implementations.
In this case annotating the top-level class in such hierarchies with `@SpringExtensionConfig(useTestClassScopedExtensionContext = true)` should resolve the issue.

2) In case you have a custom `TestExecutionListener` that overrides `prepareTestInstance(TestContext)` that suddenly no longer works, please alter the listener's implementation to look up the current test class via `testContext.getTestInstance().getClass()` instead of `testContext.getTestClass()`.

=== Spring JCL has been retired

This module has been removed in favour of Apache Commons logging, as this was a transitive dependency and the API calls aren't changing, you should experience no impact.

=== Removal of support for `javax.annotation` and `java.inject`

These annotations are no longer supported, and the `jakarta` equivalent should be used.

=== Removal of deprecated path mapping options

Several path mapping options marked as deprecated in 6.0 have been removed, such as:

* `suffixPatternMatch`/`registeredSuffixPatternMatch` for annotated controller methods
* `trailingSlashMatch` for extensions of `AbstractHandlerMapping`
* `favorPathExtension`/`ignoreUnknownPathExtensions` and underlying `PathExtensionContentNegotiationStrategy` and `ServletPathExtensionContentNegotiationStrategy` for content negotiation, configurable through `ContentNegotiationManagerFactoryBean` and in the MVC Java config
* `matchOptionalTrailingSeparator` in `PathPatternParser`

=== Removal of Undertow support

A Servlet 6.1 compatible container is needed; this also means that the undertow starter, and ability to use it as an embedded server has been dropped as Undertow is not compatible yet.

When a Servlet 6.1 compatible container is available, Undertow can still be used as a deployed server using the standard servlet support.

=== CORS Pre-Flight requests behaviour change
CORS Pre-Flight requests are no longer rejected when the CORS configuration is empty.

=== WebClient behaviour changes for Reactor Client
The `Reactor` client when used with `WebClient` will now automatically opt-in for the system properties `https.proxyHost`  and `https.proxyPort` for proxy configuration.

=== Varia

This release also contains a wide variety of smaller changes:

* `ListenableFuture` in favour of `CompletableFuture`
* Removal of `WebJars` support with `org.webjars:webjars-locator-core` in favour of `org.webjars:webjars-locator-lite`
* Removal of `OkHttp3 support`
* Renaming of `RequestContext#jstPresent` protected static field to `JSTL_PRESENT`.

=== Updated unified reachability metadata format for GraalVM native applications

This release switches to the format being adopted by the GraalVM community.
This means that we'll need to update our applications if we're contributing `RuntimeHints`.

In practise these changes boil down to:

* the resource hint syntax is now a glob pattern format rather than a `java.util.regex.Pattern` format
* registration of excludes has been removed
* registering a reflection hint or a type now also implies method, constructor and field introspection. Given this,  `ExecutableMode.INTROSPECT` and all `MemberCategory` values except `MemberCategory.INVOKE_*` have been deprecated as registering a type hint suffices. We can thus swap out `hints.reflection().registerType(MyType.class, MemberCategory.DECLARED_FIELDS);` with `hints.reflection().registerType(MyType.class);`
* `MemberCategory.PUBLIC_FIELDS` and `MemberCategory.DECLARED_FIELDS` have been renamed to `INVOKE_PUBLIC_FIELDS` and `INVOKE_DECLARED_FIELDS` respectively. Do keep in mind that you can just use simple type hints if they've only been configured for reflection.

== New

=== JSpecify

`JSpecify` nullability annotations have been added, thus if you're using Kotlin or a null checker in your build, a compilation failure might happen because some types might now be (non-)nullable. The Spring nullability annotations have been deprecated in favour of these.

=== API versioning

Both Spring MVC and WebFlux now easily allow us to version our requests.
We can configure how these versions are resolved, parsed, validated and even mark versions as deprecated to notify our consumers! The various `Client` classes such as `RestClient` and `WebTestClient` have also been enhanced so we can easily set the API version on requests.

=== BeanRegistrar

More flexible bean registration has been a wish for many of us for a long time, and this release addresses it. The new `BeanRegistrar` contract allows us to apply more complex logic, and register multiple beans.

=== RestTestClient

This non-reactive variant of `WebTestClient` can be used toi test live servers, and mock setups with a fluent API.
It can be bound to a live server, an MVC `@Controller` or the application context.

I recommend looking at the https://docs.spring.io/spring-framework/reference/7.0-SNAPSHOT/testing/resttestclient.html#page-title[official documentation].

=== Easier message converters configuration

We can now more easily set up, and facilitate the detection of HTTP message converters through `HttpMessageConverters`, which we can, for example, leverage in `WebMvcConfigurer#configureMessageConverters`, or `RestClient` and `RestTemplate`.

=== Enhanced `Optional` support in SpEL expressions

We can now call null-safe operations in `Optional` types with transparent mapping, and use the Elvis operator to automatically unwrap an `Optional`.

[source,Java]
----
@Value("#{userService.findBy(#SSN)?.orElse('Doe')}")
private String name;
----

=== Test application context pausing

As of this release, an application context cache in the test context cache will be stopped when it is no longer in active use and will automatically restart it as needed. This helps reduce the number of running background processes.

=== Bean overrides for non-singleton beans

We can now apply bean overrides such as `@TestBean` and `@MockitoSpyBean`  to non-singleton beans like prototype or custom scoped beans.

=== Improved Dependency Injection in `@Nested` Test Class Hierarchies

The `SpringExtension` for `JUnit Jupiter` now supports dependency injection into test classes and fields in `@Nested` test class hierarchies using the same `ApplicationContext` that was used to perform dependency injection into lifecycle and test methods such as `@Test`, `@BeforeEach` et cetera.
This facilitates a more consistent model for `@Nested` tests.

Normally speaking, we shouldn't encounter any issues, but in case we do bump into some, we can reference this https://github.com/spring-projects/spring-framework/wiki/Spring-Framework-7.0-Release-Notes#springextension-extension-context-scope[release note section].

=== Http Interface Client support for `Input-` and `OutputStream`

The client now supports streaming request and response bodies using `Input-` and `OutputStream` respectively.
This is quite a useful enhancement when dealing with large volumes of data, given that not everything needs to be loaded in memory anymore. This will facilitate scaling and improve the performance.

=== Context propagation for Kotlin Coroutines

We can now add the new https://docs.spring.io/spring-framework/reference/7.0/languages/kotlin/coroutines.html#coroutines.propagation[PropagationContextElement] operator to our functions to enable context propagation. The Spring team is looking into ways to automate this in a future release.

=== Google Gson support in WebFlux

Two new codecs for JSON (de)serialization in WebFlux have been added: `GsonEncoder` & `GsonDecoder`.

The Gson library itself does not support decoding JSON in a non-blocking manner, thus the `GsonDecoder` does not support decoding to `Flux<*>` types. It does however support `NDJSON` for streaming when serializing to JSON.

== Deprecations

* `RestTemplate` has been marked as deprecated in the reference documentation in favour of `RestClient`, and will formally be deprecated in Spring Framework 7.1. For further information, I recommend reading the https://spring.io/blog/2025/09/30/the-state-of-http-clients-in-spring["the state of HTTP clients"] blog post.
* The `<mvc:*` XML configuration namespace for Spring MVC is now deprecated in favour of the Java configuration variant.
* Templating support for Kotlin scripts has been deprecated given the Kotlin team plans to remove https://jcp.org/en/jsr/detail?id=223[JSR 233] support in a future Kotlin 2.x release.
* JUnit 4 support in the Spring TestContext framework has been deprecated in favour of the `SpringExtension` for JUnit JUpiter. So if you're using `SpringRunner`, `SpringClassRule`, `SpringMethodRule`, et cetera please prepare and already migrate to JUnit Jupiter.
* Jackson 2.x support has been deprecated in favour of Jackson 3.x.
* `PathMatcher` is now deprecated, please switch to `PathPatternParser` instead.
* `HandlerMappingIntrospector` has been deprecated given Spring Security works without this if all handler mappings use `PathPatternParser`, and the alternative `PathMatcher` is also deprecated.
* Certain `HttpStatus` constants have been deprecated in favour of replacements that align more closely with https://www.rfc-editor.org/rfc/rfc9110.html[RFC9110].
* `The org.springframework.web.servlet.view.document` and `org.springframework.web.servlet.view.feed` and all their types have been deprecated. The plan is for standalone libraries to enhance broader and more flexible support for these formats.
* `BeanShell` scripting support has been deprecated since there is no active maintenance anymore
* The `<lang:*` XML configuration namespace (used with `groovy` and `std` for example) is now deprecated as it's no longer being actively maintained. As it stands, there's no annotation-driven alternative, nor intent to provide one.

== Varia

As always, there are changes under the hood that developers might not notice, but will certainly offer benefits.

=== Class-file API usage for Java 24+ applications

Spring will now leverage the new class-file API introduced in https://openjdk.org/jeps/484[JEP-484] to read and write classes as Java bytecode instead of the classical reduced ASM fork that was being used.
This change will be fully transparent for applications.

== Thoughts

== References

* https://github.com/spring-projects/spring-framework/wiki/Spring-Framework-7.0-Release-Notes [Spring framework 7 release notes]