= Spring Framework 7
:toc:
:toc-placement:
:toclevels: 3

Spring Framework 7 will release in November 2025.

== Minimum requirement changes

Certain baselines have been raised, so keep these in mind if you're using them:

* A Servlet 6.1 compatible container
* JPA 3.2
* Bean Validation 3.1
* GraalVM 24 with the https://www.graalvm.org/latest/reference-manual/native-image/metadata/[new extract reachability metadata format]
* Kotlin 2.2
*  Netty 4.2
* JSONAssert 2.0

== Upgrading

=== Spring JCL has been retired

This module has been removed in favour of Apache commons logging, as this was a transitive dependency and the API calls aren't changing you should experience no impact.

=== Removal of support for `javax.annotation` and `java.inject`

These annotations are no longer supported, and the `jakarta` equivalent should be used.

=== Removal of deprecated path mapping options

The path mapping options that were marked as deprecated in 6.0 have been removed.

For example:

* `matchOptionalTrailingSeparator`
* `ignoreUnknownPathExtensions`
* `trailingSlashMatch`
* `PathExtensionContentNegotiationStrategy`

== New

=== API versioning

Both Spring MVC and WebFlux now easily allow us to version our requests.
We can configure how these versions are resolve, parsed, validated and even mark versions as deprecated to notify our consumers! The various `Client` classes such as `RestClient` and `WebTestClient` have also been enhanced so we can easily set the API version on requests.

=== BeanRegistrar

More flexible bean registration has been a wish for many of us for a long time, and this release addresses it. The new `BeanRegistrar` contract allows us to apply more complex logic, and register multiple beans.

=== RestTestClient

This non-reactive variant of `WebTestClient` can be used toi test live servers, and mock setups with a fluent API.
It can be bound to a live server, an MVC `@Controller` or the application context.

I recommend looking at the https://docs.spring.io/spring-framework/reference/7.0-SNAPSHOT/testing/resttestclient.html#page-title[official documentation].

=== Easier message converters configuration

We can now more easily setup, and facilitate the detection of HTTP message converters through `HttpMessageConverters`, which we can for example leverage in `WebMvcConfigurer#configureMessageConverters`.

=== Enhanced `Optional` support in SpEL expressions

We can now call null-safe operations ib `Optional` types with transparent mapping, and use the Elvis operator to automatically unwrap an `Optional`.

[source,Java]
----
@Value("#{userService.findBy(#SSN)?.orElse('Doe')}")
private String name;
----

=== Test application context pausing

As of this release an application context cache in the test context cache will be stopped when it is no longer in active use, and will automatically restart it as needed. This helps reduce the number of running background processes.

=== Http Interface Client support for `Input-` and `OutputStream`

The client now supports streaming request and response bodies using `Input-` and `OutputStream` respectively.
This quite a useful enhancement when dealing with large volumes of data, given that not everything needs to be loaded in memory anymore. This will facilitate scaling and improve the performance.

== Varia

As always, there are changes under the hood that developers might not notice, but will certainly offer benefits.

=== Class-file API usage for Java 24+ applications

Spring will now leverage the new class-file API introduced in https://openjdk.org/jeps/484[JEP-484] to read and write classes as Java bytecode instead of the classical reduced ASM fork that was being used.
This change will be fully transparant for applications.

== Thoughts

== References

* https://github.com/spring-projects/spring-framework/wiki/Spring-Framework-7.0-Release-Notes [Spring framework 7 release notes]